inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Security/Eval:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Exclude:
    - '**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
