inherit_from: .rubocop_todo.yml

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 120

Security/Eval:
  Exclude:
    - 'Gemfile'

Style/Documentation:
  Exclude:
    - '**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'

Lint/Void:
  Exclude:
    - 'config/initializers/zz_occi_preload.rb'

Rails/DynamicFindBy:
  Exclude:
    - 'app/models/backends/opennebula/compute.rb'
