language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head

matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master
    - 1.0.x
    - 1.1.x

services:
    - memcached

script: bundle exec rake spec

install: 'gem install bundler -v "~> 1.7.12" && bundle install --jobs=3 --retry=3 --without stuff_breaking_travis_ci'

env:
  - ON_TRAVIS_CI=yes
