language: ruby

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.3
  fast_finish: true

branches:
  only:
    - master
    - 1.0.x
    - 1.1.x

services:
    - memcached

script: bundle exec rake spec

install: 'gem install bundler -v ">= 1.7.12" && bundle install --retry=10 --without stuff_breaking_travis_ci'

env:
  - ON_TRAVIS_CI=yes

sudo: false
