language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master

services:
  - memcached # will start memcached

script: "bundle exec rake spec"