language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

branches:
  only:
    - master

before_install:
  - sudo apt-get -y remove memcached
  - echo "yes" | sudo add-apt-repository ppa:travis-ci/memcached-sasl
  - sudo apt-get update
  - sudo apt-get install -y memcached=1.4.13-0ubuntu2+travis1
  - sudo service memcached start

script: "bundle exec rake spec"
