language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master

services:
  - mongodb # will start mongodb-server
  - memcached # will start memcached

script: "bundle exec rake spec"