protocol: http
hostname: localhost
port: 11443
authn_strategies:
  - basic
  - x509
  - voms
hooks:
  - dummy
backend: dummy
log_level: debug
tempdir: /tmp/rocci_server
force_ssl: false
memcaches:
  - 'localhost:11211'
