# Keystone URI (as it appears in the WWW-Authenticate HTTP header)
keystone_uri: <%= ENV['ROCCI_SERVER_AUTHN_KEYSTONE_URI'] || 'http://localhost:5000/' %>

# X.509 stuff
# cert_source  -- read certificates from 'file' or 'url'
# ca_path      -- path to a directory with CA certificates
# ca_cert      -- the file from http://[KEYSTONE_FQDN]:35357/v2.0/certificates/ca or URL
# signing_cert -- the file from http://[KEYSTONE_FQDN]:35357/v2.0/certificates/signing or URL
# trl_url      -- http://[KEYSTONE_FQDN]:35357/v2.0/tokens/revoked
keystone_pki_trust:
  cert_source: 'file'
  ca_cert: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'authn_strategies', 'keystone', 'certificates', 'ca_cert.pem') %>
  signing_cert: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'authn_strategies', 'keystone', 'certificates', 'signing_cert.pem') %>
  trl_url: <%= ENV['ROCCI_SERVER_AUTHN_KEYSTONE_TRL_URL'] || 'http://localhost:35357/v2.0/tokens/revoked' %>

# Pool of memcache servers, at least one is required
memcaches: <%= ENV['ROCCI_SERVER_AUTHN_KEYSTONE_MEMCACHES'] || 'localhost:11211' %>

# Mapping to local user and tenant names
tenant_mapping: 'false'
user_mapping: 'false'
# YAML file with the following syntax
#
# old_name: 'new_name'
# another_old_name: 'another_new_name'
user_mapfile: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'authn_strategies', 'keystone', 'files', 'user_mapfile.yml') %>
tenant_mapfile: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'authn_strategies', 'keystone', 'files', 'tenant_mapfile.yml') %>

# Allow all tenants except the ones in the blacklist
# or allow only those found in the whitelist. Evaluation
# is done BEFORE the tenant name mapping is applied!
access_policy: 'blacklist' # or 'whitelist'
# YAML files with the following syntax
#
# - tenant_name
# - another_tenant_name
# - yet_another_tenant_name
whitelist: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'authn_strategies', 'keystone', 'files', 'whitelist.yml') %>
blacklist: <%= File.join(Rails.application.config.rocci_server_etc_dir, 'authn_strategies', 'keystone', 'files', 'blacklist.yml') %>
