# General configuration
defaults: &default
  hostname: localhost
  port: 3000
  authn:
    - dummy
  hooks:
    - dummy
  backend: dummy
  log_level: debug
  tempdir: /tmp
  force_ssl: false

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  hostname: your.host.org
  port: 11443
  authn:
    - basic
    - x509
    - voms
  hooks:
    - autocreate_user
  backend: opennebula
  log_level: warn
  force_ssl: true